[package]
name = "rust_clay"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"
bindgen = { version = "0.71.1", optional = true }

[features]
default = []

# Activating this feature will use the built bindings instead of the static included ones
build-clay = [ "dep:bindgen" ]
